// The `verified` flag is permanently false for every species right now —
// nothing in this app has a review workflow that ever flips it to true yet
// (2026-09-02, flagged by Jaideep: the "generated by AI, not yet reviewed"
// banner was showing on the hand-curated seed catalog too, which is simply
// wrong — those entries cite real sources, they were never AI-generated).
// Until a real review step exists, "was this actually AI-generated" is the
// honest question to show a disclosure for, and `origin` already answers
// it precisely — use that instead of `verified` everywhere in the UI.
export function isAiGenerated(species: { origin?: string | null } | null | undefined): boolean {
  return species?.origin === "ai_generated";
}
