// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit by hand.
// Regenerate with: npm run db:generate

export type Migration = { tag: string; when: number; statements: string[] };

export const migrations: Migration[] = [
  {
    "tag": "0000_deep_mauler",
    "when": 1788190135881,
    "statements": [
      "CREATE TABLE `ai_interactions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text,\n\t`kind` text,\n\t`prompt_version` text NOT NULL,\n\t`user_input` text,\n\t`grounding_refs` text,\n\t`response` text,\n\t`input_tokens` integer,\n\t`output_tokens` integer,\n\t`cost_usd` real,\n\t`latency_ms` integer,\n\t`rating` integer,\n\t`correction_text` text,\n\t`created_at` text NOT NULL\n);",
      "CREATE TABLE `dex_cards` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`species_id` text NOT NULL,\n\t`unlocked_at` text,\n\t`unlock_source` text,\n\t`times_kept` integer,\n\t`first_photo_uri` text,\n\t`created_at` text NOT NULL\n);",
      "CREATE TABLE `dismissed_warnings` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text,\n\t`livestock_id` text,\n\t`warning_key` text NOT NULL,\n\t`dismissed_at` text NOT NULL\n);",
      "CREATE TABLE `equipment` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`subtype` text,\n\t`brand` text,\n\t`model` text,\n\t`wattage` real,\n\t`rated_lph` real,\n\t`installed_on` text,\n\t`service_interval_days` integer,\n\t`last_serviced_on` text,\n\t`notes` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `livestock` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`species_id` text NOT NULL,\n\t`nickname` text,\n\t`count` integer DEFAULT 1 NOT NULL,\n\t`added_on` text NOT NULL,\n\t`removed_on` text,\n\t`status` text,\n\t`death_cause` text,\n\t`source` text,\n\t`notes` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `livestock_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`livestock_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`occurred_at` text NOT NULL,\n\t`note` text,\n\t`photo_uri` text,\n\t`created_at` text NOT NULL\n);",
      "CREATE TABLE `log_entries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`type` text,\n\t`body` text,\n\t`occurred_at` text NOT NULL,\n\t`water_changed_pct` real,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `measurements` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`parameter_id` text NOT NULL,\n\t`value` real NOT NULL,\n\t`measured_at` text NOT NULL,\n\t`method` text,\n\t`note` text,\n\t`photo_uri` text,\n\t`created_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `parameter_defs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text,\n\t`name` text NOT NULL,\n\t`unit` text NOT NULL,\n\t`target_min` real,\n\t`target_max` real,\n\t`decimals` integer,\n\t`sort_order` integer,\n\t`is_active` integer,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE TABLE `photos` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text,\n\t`livestock_id` text,\n\t`log_entry_id` text,\n\t`scan_id` text,\n\t`local_uri` text NOT NULL,\n\t`caption` text,\n\t`taken_at` text,\n\t`width` integer,\n\t`height` integer,\n\t`bytes` integer,\n\t`created_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `plants` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`species_id` text,\n\t`common_name` text,\n\t`planted_on` text,\n\t`quantity` integer,\n\t`light_need` text,\n\t`co2_need` text,\n\t`trim_interval_days` integer,\n\t`last_trimmed_on` text,\n\t`notes` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `push_sends` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`task_id` text NOT NULL,\n\t`subscription_id` text NOT NULL,\n\t`sent_at` text NOT NULL,\n\t`status` text NOT NULL\n);",
      "CREATE TABLE `push_subscriptions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`device_label` text,\n\t`subscription_json` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`last_seen_at` text\n);",
      "CREATE TABLE `scans` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`image_uri` text NOT NULL,\n\t`model_name` text NOT NULL,\n\t`model_version` text,\n\t`prompt_version` text NOT NULL,\n\t`raw_response` text NOT NULL,\n\t`findings` text,\n\t`scores` text,\n\t`user_corrections` text,\n\t`created_at` text NOT NULL\n);",
      "CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text\n);",
      "CREATE TABLE `species` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`scientific_name` text NOT NULL,\n\t`common_names` text,\n\t`common_names_in` text,\n\t`category` text,\n\t`verified` integer DEFAULT false NOT NULL,\n\t`source_refs` text,\n\t`temp_c_min` real,\n\t`temp_c_max` real,\n\t`ph_min` real,\n\t`ph_max` real,\n\t`hardness_dgh_min` real,\n\t`hardness_dgh_max` real,\n\t`adult_size_cm` real,\n\t`min_volume_l` real,\n\t`min_footprint_length_cm` real,\n\t`min_footprint_width_cm` real,\n\t`social_min_group` integer,\n\t`temperament` text,\n\t`swim_level` text,\n\t`diet` text,\n\t`difficulty` text,\n\t`lifespan_min_years` real,\n\t`lifespan_max_years` real,\n\t`breeding` text,\n\t`care_notes` text,\n\t`common_mistakes` text,\n\t`incompatible_with` text,\n\t`disputed` text,\n\t`origin` text NOT NULL,\n\t`uncertainty_note` text,\n\t`ai_confidence` text,\n\t`flags` text,\n\t`dex_rarity` text,\n\t`dex_tier` integer,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE TABLE `tanks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`photo_uri` text,\n\t`length_cm` real NOT NULL,\n\t`width_cm` real NOT NULL,\n\t`height_cm` real NOT NULL,\n\t`volume_l` real NOT NULL,\n\t`shape` text,\n\t`status` text,\n\t`water_type` text,\n\t`is_planted` integer,\n\t`has_co2` integer,\n\t`city` text,\n\t`started_on` text,\n\t`substrate` text,\n\t`notes` text,\n\t`archived_at` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`tank_id` text NOT NULL,\n\t`livestock_id` text,\n\t`title` text NOT NULL,\n\t`preset_type` text,\n\t`rrule` text,\n\t`next_due_at` text,\n\t`last_done_at` text,\n\t`is_active` integer,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`deleted_at` text\n);"
    ]
  },
  {
    "tag": "0001_cloudy_exodus",
    "when": 1788276524579,
    "statements": [
      "CREATE TABLE `profile` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`city` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);"
    ]
  },
  {
    "tag": "0002_gigantic_ogun",
    "when": 1788278170509,
    "statements": [
      "ALTER TABLE `tanks` ADD `setup_type` text;"
    ]
  },
  {
    "tag": "0003_lean_hemingway",
    "when": 1788321498065,
    "statements": [
      "ALTER TABLE `species` ADD `image_uri` text;"
    ]
  },
  {
    "tag": "0004_brave_krista_starr",
    "when": 1788437446506,
    "statements": [
      "CREATE TABLE `species_suggestions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`suggested_name` text NOT NULL,\n\t`note` text,\n\t`photo_uri` text,\n\t`ai_candidates` text,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`reviewed_at` text\n);"
    ]
  },
  {
    "tag": "0005_breezy_sunspot",
    "when": 1788449878447,
    "statements": [
      "ALTER TABLE `profile` ADD `email` text;",
      "ALTER TABLE `profile` ADD `contact` text;",
      "ALTER TABLE `profile` ADD `photo_uri` text;"
    ]
  },
  {
    "tag": "0006_amusing_zarek",
    "when": 1788453539102,
    "statements": [
      "ALTER TABLE `profile` ADD `username` text;"
    ]
  }
];
